#!/bin/bash

set -euo pipefail  # 启用严格模式

# 默认参数值
DEFAULT_POLARIS_SERVER_ADDR="127.0.0.1:8091"
DNS_BACK_DIR="./"
POLARIS_SERVER_ADDR=""

# 显示帮助信息
show_help() {
    echo "Usage: $0 [-s polaris_server_addr] [-b dns_back_dir]"
    echo "Options:"
    echo "  -s  Polaris server address (default: ${DEFAULT_POLARIS_SERVER_ADDR})"
    echo "  -b  DNS configuration backup directory (default: ${DNS_BACK_DIR})"
    echo "  -h  Show this help message"
    exit 0
}

# 解析命令行参数
while getopts ':b:s:h' OPT; do
    case $OPT in
    b) DNS_BACK_DIR="$OPTARG" ;;
    s) POLARIS_SERVER_ADDR="$OPTARG" ;;
    h) show_help ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        show_help
        exit 1
        ;;
    :)
        echo "Option -$OPTARG requires an argument." >&2
        show_help
        exit 1
        ;;
    esac
done

# 设置默认值
if [[ -z "$POLARIS_SERVER_ADDR" ]]; then
    POLARIS_SERVER_ADDR="$DEFAULT_POLARIS_SERVER_ADDR"
fi

echo "=== Polaris Sidecar Installation ==="
echo "[INFO] Polar server address: ${POLARIS_SERVER_ADDR}"
echo "[INFO] DNS backup directory: ${DNS_BACK_DIR}"

# 确保备份目录存在
mkdir -p "${DNS_BACK_DIR}"

# 安装Polaris Sidecar
install_polaris_sidecar() {
    echo -e "\n[STEP 1] Checking for existing polaris-sidecar processes..."

    # 使用pgrep更可靠地检查进程
    if pgrep -f polaris-sidecar >/dev/null; then
        echo "[ERROR] polaris-sidecar is already running. Please stop it before installation."
        exit 1
    fi

    echo "[STEP 2] Locating polaris-sidecar package..."

    # 使用mapfile安全处理命令输出 (修复ShellCheck警告)
    local polaris_pkgs=()
    while IFS= read -r -d $'\0' file; do
        polaris_pkgs+=("$file")
    done < <(find . -maxdepth 1 -name "polaris-sidecar-release*.zip" -print0)

    if [ ${#polaris_pkgs[@]} -eq 0 ]; then
        echo "[ERROR] No polaris-sidecar package found in current directory."
        exit 1
    elif [ ${#polaris_pkgs[@]} -gt 1 ]; then
        echo "[ERROR] Multiple polaris-sidecar packages found:"
        printf '  %s\n' "${polaris_pkgs[@]}"
        echo "Please ensure only one package is present."
        exit 1
    fi

    local pkg_file="${polaris_pkgs[0]}"
    local extract_dir="${pkg_file%.zip}"

    echo "[STEP 3] Extracting package: ${pkg_file}..."
    if [ -d "$extract_dir" ]; then
        echo "[WARN] Existing directory found: ${extract_dir}, removing..."
        rm -rf "$extract_dir"
    fi

    if ! unzip -q "$pkg_file"; then
        echo "[ERROR] Failed to extract package: ${pkg_file}"
        exit 1
    fi

    pushd "$extract_dir" >/dev/null

    echo "[STEP 4] Starting polaris-sidecar..."
    export POLARIS_ADDRESS="$POLARIS_SERVER_ADDR"
    echo "[INFO] Using POLARIS_ADDRESS=${POLARIS_ADDRESS}"

    # 确保脚本可执行
    if [ ! -x "./tool/start.sh" ]; then
        chmod +x ./tool/start.sh
    fi

    if ! ./tool/start.sh; then
        echo "[ERROR] Failed to start polaris-sidecar"
        popd >/dev/null
        exit 1
    fi

    popd >/dev/null
    echo -e "[SUCCESS] polaris-sidecar installed and started successfully\n"
}

# 配置DNS
configure_dns() {
    echo "[STEP 5] Configuring system DNS settings..."
    local resolv_conf="/etc/resolv.conf"
    local timestamp
    timestamp=$(date "+%Y%m%d_%H%M%S")
    local backup_file="${DNS_BACK_DIR}/resolv.conf.bak_${timestamp}"

    if [ ! -f "$resolv_conf" ]; then
        echo "[WARN] DNS configuration file not found: ${resolv_conf}"
        return
    fi

    echo "[INFO] Backing up current DNS config to: ${backup_file}"
    if ! cp "$resolv_conf" "$backup_file"; then
        echo "[ERROR] Failed to backup DNS configuration"
        exit 1
    fi

    echo "[INFO] Updating DNS configuration..."
    cat <<EOF | sudo tee "$resolv_conf" >/dev/null
# Generated by polaris-sidecar installer
# DO NOT EDIT MANUALLY - CHANGES WILL BE OVERWRITTEN

nameserver 127.0.0.1

# Original configuration (backup: ${backup_file})
$(cat "$backup_file")
EOF

    echo "[SUCCESS] DNS configuration updated\n"
}

# 验证安装
verify_installation() {
    echo "[STEP 6] Verifying installation..."
    if ! pgrep -f polaris-sidecar >/dev/null; then
        echo "[ERROR] polaris-sidecar process not found after installation"
        exit 1
    fi

    echo "[INFO] Running test DNS query..."
    if dig +short polaris.checker.polaris @127.0.0.1 >/dev/null; then
        echo "[SUCCESS] Test DNS query succeeded"
    else
        echo "[WARN] Test DNS query failed, but installation completed"
    fi
}

# 主安装流程
configure_dns
install_polaris_sidecar
verify_installation

echo "=== Installation Completed ==="
echo "Polaris Sidecar is now running and DNS is configured"
echo "To verify manually: dig polaris.checker.polaris"
